name: twitter_clone
description: A twitter app clone for learning purposes.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  stacked_shared: any
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/twitter-logo.png

